apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstackspringbootangular_2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fullstackspringbootangular_2
  template:
    metadata:
      labels:
        app: fullstackspringbootangular_2
    spec:
      containers:
      - name: nginx-test
        image: "docker.io/mariamwafik333/fullstackspringbootangular_2:latest"
        ports:
        - containerPort: 80
